export const Permission = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',

  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_USERS: 'VIEW_USERS',

  VIEW_SISWA: 'VIEW_SISWA',
  EDIT_SISWA: 'EDIT_SISWA',

  MANAGE_ATTENDANCE: 'MANAGE_ATTENDANCE',
  SCAN_QR: 'SCAN_QR',

  MANAGE_ACADEMIC: 'MANAGE_ACADEMIC',
  INPUT_NILAI: 'INPUT_NILAI',
  APPROVE_RAPOR: 'APPROVE_RAPOR',

  VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',

  ACCESS_AI: 'ACCESS_AI',
  USE_AI_ASSISTANT: 'USE_AI_ASSISTANT',

  MANAGE_SYSTEM: 'MANAGE_SYSTEM',
  ACCESS_DEVELOPER_CONSOLE: 'ACCESS_DEVELOPER_CONSOLE',
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];
